services:
  ftp-server:
    image: delfer/alpine-ftp-server:latest
    container_name: recepcionactiva-ftp
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - USERS=usermw|usermw|/home/usermw|1000
      - ADDRESS=localhost
    volumes:
      - ./ftp-data:/home/usermw
    restart: unless-stopped
    networks:
      - ftp-network

  ftp-http-server:
    image: nginx:alpine
    container_name: recepcionactiva-ftp-http
    ports:
      - "8080:80"
    volumes:
      - ./ftp-data:/usr/share/nginx/html:ro
      - ./nginx-ftp.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ftp-server
    restart: unless-stopped
    networks:
      - ftp-network

networks:
  ftp-network:
    driver: bridge
